# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93656c850a1154bacd50bcbcf7c89717595f65595c6a29c76e0230e09cf07195ccebccfecac1168a8c2b4206cc2877fe8f5c166f1575160c878afc56181ee4e5

test:
  secret_key_base: 4aa83d4e0798b996ffc953b985fb046a47193bfb90a8de6ecce12aa967ceeac4cb6bbc9b4f4f9c72afe6b763f20aca5d06af3b3be2a79603b8e0ca2f8cebeaac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
